---
name: Deploy Lambda - Authorizer
run-name: >-
  ${{
    github.event_name == 'push'
    && github.event.head_commit.message
    || format('Manual deploy #{0}', github.run_number)
  }}

on:
  push:
    branches:
      - main
    paths:
      - 'services/authorizer/**'
      - '.github/workflows/deploy-lambda_authorizer.yml'
      - '.github/workflows/template_tests-*.yml'

jobs:
  unit-tests:
    uses: ./.github/workflows/template_tests-ut.yml
    with:
      service-name: 'authorizer'

#  e2e-tests:
#    needs: unit-tests
#    uses: ./.github/workflows/tests-e2e.yml

#  deploy:
#    needs: e2e-tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy
#        run: echo "Deploy goes here"
