---
name: "Deploy - Global Infrastructure"
run-name: >-
  ${{
    github.event_name == 'push'
    && github.event.head_commit.message
    || format('Manual deploy #{0}', github.run_number)
  }}

on:
  push:
    branches:
      - main
    paths:
      - 'infra/global/**'
      - 'deploy_infra-global.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  qa:
    name: QA Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform QA
        uses: ./.github/actions/terraform-qa
        with:
          working-directory: infra/global

  deploy:
    name: Deploy
    needs: qa
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: infra/global

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - name: Install Just
        uses: extractions/setup-just@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init --backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" --backend-config="region=eu-west-1"

      - name: Terraform Init
        run: just workspace dev

      - name: Terraform Plan
        run: just plan dev

#      - name: Terraform Apply
#        run: just apply dev --auto-approve
